package fun.hijklmn.pojo;

import java.util.Date;

public class Job {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_id
     *
     * @mbg.generated Wed Oct 30 15:04:54 CST 2019
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_name
     *
     * @mbg.generated Wed Oct 30 15:04:54 CST 2019
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_desc
     *
     * @mbg.generated Wed Oct 30 15:04:54 CST 2019
     */
    private String jobDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.create_time
     *
     * @mbg.generated Wed Oct 30 15:04:54 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.update_time
     *
     * @mbg.generated Wed Oct 30 15:04:54 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_id
     *
     * @return the value of job.job_id
     *
     * @mbg.generated Wed Oct 30 15:04:54 CST 2019
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_id
     *
     * @param jobId the value for job.job_id
     *
     * @mbg.generated Wed Oct 30 15:04:54 CST 2019
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_name
     *
     * @return the value of job.job_name
     *
     * @mbg.generated Wed Oct 30 15:04:54 CST 2019
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_name
     *
     * @param jobName the value for job.job_name
     *
     * @mbg.generated Wed Oct 30 15:04:54 CST 2019
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_desc
     *
     * @return the value of job.job_desc
     *
     * @mbg.generated Wed Oct 30 15:04:54 CST 2019
     */
    public String getJobDesc() {
        return jobDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_desc
     *
     * @param jobDesc the value for job.job_desc
     *
     * @mbg.generated Wed Oct 30 15:04:54 CST 2019
     */
    public void setJobDesc(String jobDesc) {
        this.jobDesc = jobDesc == null ? null : jobDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.create_time
     *
     * @return the value of job.create_time
     *
     * @mbg.generated Wed Oct 30 15:04:54 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.create_time
     *
     * @param createTime the value for job.create_time
     *
     * @mbg.generated Wed Oct 30 15:04:54 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.update_time
     *
     * @return the value of job.update_time
     *
     * @mbg.generated Wed Oct 30 15:04:54 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.update_time
     *
     * @param updateTime the value for job.update_time
     *
     * @mbg.generated Wed Oct 30 15:04:54 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}